In [2]:
# CELL 0 

import numpy as np
import pandas as pd

# Your Lab Details
STUDENT_NAME = "Jade Axelle Funa"
STUDENT_ID = 6495

In [3]:
# CELL 1

np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)
mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

Jade Axelle Funa's Array: [ 53 118  68  56  50 133 104  42 122 123]
Mean: 86.9 Std Dev: 34.29125252888847


In [4]:
# CELL 2 

np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)
row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Jade Axelle Funa's Matrix:
 [[53 54 23 48]
 [53  4 18 39]
 [57 56 50  5]]
Row sums: [178 114 168]
Column sums: [163 114  91  92]


In [5]:
# CELL 3 

np.random.seed(STUDENT_ID)
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)
slice_mid = arr3d[:, 1, :]
print("Slice[:, 1, :]:\n", slice_mid)

Jade Axelle Funa's 3D Array:
 [[[20 21 22]
  [15 20  3]
  [17  6 24]]

 [[23 17  4]
  [20  7 17]
  [ 9  5  7]]

 [[13  4  5]
  [14  8 20]
  [ 5 11  8]]]
Slice[:, 1, :]:
 [[15 20  3]
 [20  7 17]
 [14  8 20]]


In [6]:
# CELL 4 

np.random.seed(STUDENT_ID)
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x > STUDENT_ID % 50) & (x < STUDENT_ID % 100)]
print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Jade Axelle Funa's Original: [ 53 118  68  56  50 133 104  42 122 123]
Filtered subset: [53 68 56 50]


In [7]:
# CELL 5 

np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
print("Matrix A:\n", A)
print("Matrix B:\n", B)
product = A @ B
det_A = np.linalg.det(A)
print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[53 54]
 [23 48]]
Matrix B:
 [[53  4]
 [18 39]]
A @ B:
 [[3781 2318]
 [2083 1964]]
Determinant of A: 1302.0000000000007


In [8]:
# CELL 6

angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)
print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Jade Axelle Funa's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [ ]:
# CELL 7 

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Jade Axelle Funa's Modified 4x4 Array:
 [[ 0 54  0 48]
 [53  4 18 39]
 [ 0 56  0  5]
 [21 40 50 42]]


In [10]:
# CELL 8

np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores >= STUDENT_ID % 70, 'Pass', 'Fail')
print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

Jade Axelle Funa's Scores: [ 52 117  67  55  49 132 103  41 121 122]
Grades: ['Fail' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass']


In [11]:
# CELL 9

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
flat_arr = arr.flatten()
transposed_arr = arr.T
print("Original:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original:
 [[53 54 23 48]
 [53  4 18 39]
 [57 56 50  5]]
Flattened: [53 54 23 48 53  4 18 39 57 56 50  5]
Transposed:
 [[53 53 57]
 [54  4 56]
 [23 18 50]
 [48 39  5]]


In [12]:
# CELL 10 

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,3))
mask = arr % 2 == 0
arr[mask] = -1
print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[53 -1 23]
 [-1 53 -1]
 [-1 39 57]]


In [13]:
# CELL 11 

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Name': [STUDENT_NAME] * 5,
    'Score': np.random.randint(STUDENT_ID % 50, STUDENT_ID % 100 + 50, 5),
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5)
})
print(df)

               Name  Score  YearsCodePro
0  Jade Axelle Funa     97            17
1  Jade Axelle Funa    131             6
2  Jade Axelle Funa     92            24
3  Jade Axelle Funa     97            23
4  Jade Axelle Funa    112            17


In [15]:
# CELL 12 

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)

EdLevel
Bachelor     84913.5
Master       96212.5
PhD         100118.0
Name: ConvertedComp, dtype: float64


In [16]:
# CELL 13 

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)

       Country  ConvertedComp
4      Germany         107508
2           UK         100118
3       Canada          94447
1          USA          84917
0  Philippines          75380


In [17]:
# CELL 14 

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Name': [STUDENT_NAME] * 5,
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5)
})
high_exp = df[df['YearsCodePro'] > STUDENT_ID % 10]
print(high_exp)

               Name  YearsCodePro
0  Jade Axelle Funa            20
1  Jade Axelle Funa            21
2  Jade Axelle Funa            22
3  Jade Axelle Funa            15
4  Jade Axelle Funa            20


In [18]:
# CELL 15

np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)

   ConvertedComp   Bracket
0          75380   50-100k
1          84917   50-100k
2         100118  100-150k
3          94447   50-100k
4         107508  100-150k


In [19]:
# CELL 16

np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
df['LogComp'] = np.log(df['ConvertedComp'])
print(df)

   ConvertedComp    LogComp
0          75380  11.230297
1          84917  11.349430
2         100118  11.514105
3          94447  11.455794
4         107508  11.585321


In [20]:
# CELL 17 

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5),
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
print(df.corr())

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000       0.774231
ConvertedComp      0.774231       1.000000


In [21]:
# CELL 18

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean', 'median', 'std']).reset_index()
print(summary)

    EdLevel      mean    median           std
0  Bachelor   84913.5   84913.5  13482.404997
1    Master   96212.5   96212.5  15974.249294
2       PhD  100118.0  100118.0           NaN


In [22]:
# CELL 19 

np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
df['HighPay'] = np.where(df['ConvertedComp'] > 110000, 'Yes', 'No')
print(df)

   ConvertedComp HighPay
0          75380      No
1          84917      No
2         100118      No
3          94447      No
4         107508      No


In [23]:
# CELL 20 

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top_stats = df.groupby('Country')['ConvertedComp'].agg(['mean', 'max'])
print(top_stats)

                 mean     max
Country                      
Canada        94447.0   94447
Germany      107508.0  107508
Philippines   75380.0   75380
UK           100118.0  100118
USA           84917.0   84917


In [28]:
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
zeros_array = np.zeros(10)
zeros_array[4] = 1 
print("Zeros array with 5th element as 1:\n", zeros_array)

Zeros array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [26]:
range_array = np.arange(10, 50)
print("Array from 10 to 49:\n", range_array)

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [27]:
reversed_array = range_array[::-1]
print("Reversed Array:\n", reversed_array)

Reversed Array:
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
